# Generated by Django 2.2.12 on 2021-10-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AuthorID', models.CharField(max_length=60)),
                ('FName', models.CharField(max_length=60)),
                ('LName', models.CharField(max_length=60)),
                ('Biography', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=60)),
                ('Title', models.CharField(max_length=60)),
                ('Description', models.CharField(max_length=60)),
                ('PublishDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GenreID', models.CharField(max_length=60)),
                ('Type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PublisherID', models.CharField(max_length=60)),
                ('Name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.CharField(max_length=60)),
                ('Price', models.CharField(max_length=60)),
                ('CopiesSold', models.CharField(max_length=60)),
                ('AuthorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Author')),
                ('GenreID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Genre')),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Book')),
                ('PublisherID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.Publisher')),
            ],
        ),
    ]
