# Generated by Django 2.2.12 on 2021-12-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_auto_20211202_2143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookdetails',
            options={'ordering': ['ISBN', 'AuthorID']},
        ),
    ]
